### ISSUE TITLE
Signed Response

### ISSUE THREAD

**Issue by lnyntng** [rohe/pysaml2#293]
Hi, 

I am attempting to receive an IDP signed request, but I am not sure what I need to configure in order to verify the signature.

I have set up the CONFIG as follows:

``` python
'want_response_signed': True, 
'authn_assertions_signed': True,
```

I am also sending these parameters to parse_authn_request_response:

``` python
parse_authn_request_response(
        xmlstr=request.form['SAMLResponse'],
        binding=entity.BINDING_HTTP_POST,
        outstanding_certs={
            'http://somedomain.com': [
                {
                    'key': '.../app-private.key',
                    'cert': '.../app-public.cert'
                }
            ]
        }
)
```

But I get this traceback in my error.log:

```
Traceback (most recent call last):
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Wed Dec 02 20:05:34 2015] [error]     response = self.full_dispatch_request()
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Wed Dec 02 20:05:34 2015] [error]     rv = self.handle_user_exception(e)
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 188, in wrapped_function
[Wed Dec 02 20:05:34 2015] [error]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Wed Dec 02 20:05:34 2015] [error]     reraise(exc_type, exc_value, tb)
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed Dec 02 20:05:34 2015] [error]     rv = self.dispatch_request()
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Wed Dec 02 20:05:34 2015] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 127, in wrapped_function
[Wed Dec 02 20:05:34 2015] [error]     resp = make_response(f(*args, **kwargs))
[Wed Dec 02 20:05:34 2015] [error]   File "/var/www/mysp/app.py", line 199, in idp_initiated
[Wed Dec 02 20:05:34 2015] [error]     'cert': '/var/www/mysp/app-public.cert'
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/saml2/client_base.py", line 581, in parse_authn_request_response
[Wed Dec 02 20:05:34 2015] [error]     binding, **kwargs)
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/saml2/entity.py", line 1140, in _parse_response
[Wed Dec 02 20:05:34 2015] [error]     response = response.verify(keys)
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/saml2/response.py", line 993, in verify
[Wed Dec 02 20:05:34 2015] [error]     if self.parse_assertion(keys):
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/saml2/response.py", line 908, in parse_assertion
[Wed Dec 02 20:05:34 2015] [error]     if not self._assertion(assertion, False):
[Wed Dec 02 20:05:34 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/saml2/response.py", line 770, in _assertion
[Wed Dec 02 20:05:34 2015] [error]     raise SignatureError("Signature missing for assertion")
[Wed Dec 02 20:05:34 2015] [error] SignatureError: Signature missing for assertion
```

What am I missing?

**Comment by rohe** [comment]
> 2 dec 2015 kl. 21:35 skrev lnyntng <notifications@github.com>:
> 
> Hi,
> 
> I am attempting to receive an IDP signed request, but I am not sure what I need to configure in order to verify the signature.

What you have done looks OK.
The exception is cast because the software is unable to find an assertion signature in the response.
So, it seems the IdP isn’t signing the assertion part of the response.
They might be signing the response as a whole but that’s not the same thing.

— Roland
”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by thinkt4nk** [comment]
I'm having a similar issue. I see the signature is in the response. The signature doesn't include the cert, though. Can pysaml2 not infer the cert from the asserting party's metadata?
