### ISSUE TITLE
Issue while sending unsigned SP-initiated login requests

### ISSUE THREAD

**Issue by julianvilas** [rohe/pysaml2#305]
Hi,

I'm new using the library and I encountered a problem while sending unsigned SP-initiated login requests, probably due to my lack of knowledge/experience with it.

This is my testing env:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```
```
$ uname -a
Linux hostname 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Commit: 01e0fafe855280ed164789748411486a7f796a70

I've connected my Flask-based python application with OKTA, using as a reference the example published in https://github.com/jpf/okta-pysaml2-example. The idP-initiated login is working well, but the SP-initiated fails.

The error I get is:
```
INFO:saml2.entity:HTTP REDIRECT
ERROR:__main__:Exception on /saml/login [GET]
Traceback (most recent call last):
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "pysaml-okta/hello.py", line 111, in sp_initiated
    reqid, info = saml_client.prepare_for_authenticate()
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/saml2/client.py", line 81, in prepare_for_authenticate
    **kwargs)
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/saml2/client.py", line 134, in prepare_for_negotiated_authenticate
    relay_state, sigalg=sigalg)
  File "/home/ubuntu/pyenvs/pysaml-okta/local/lib/python2.7/site-packages/saml2/entity.py", line 228, in apply_binding
    signer = self.sec.sec_backend.get_signer(kwargs['sigalg'])
AttributeError: 'NoneType' object has no attribute 'get_signer'
INFO:werkzeug:127.0.0.1 - - [22/Jan/2016 14:16:23] "GET /saml/login HTTP/1.1" 500 -
```

I'm using a config like this:
````
    settings = {
        'metadata': {
            "local": [metadata_location]
            },
        'service': {
            'sp': {
                'endpoints': {
                    'assertion_consumer_service': [
                        (acs_url, BINDING_HTTP_REDIRECT),
                        (acs_url, BINDING_HTTP_POST),
                        (https_acs_url, BINDING_HTTP_REDIRECT),
                        (https_acs_url, BINDING_HTTP_POST)
                    ],
                },
                # Don't verify that the incoming requests originate from us via
                # the built-in cache for authn request ids in pysaml2
                'allow_unsolicited': True,
                # Don't sign authn requests, since signed requests only make
                # sense in a situation where you control both the SP and IdP
                'authn_requests_signed': False,
                'logout_requests_signed': True,
                'want_assertions_signed': True,
                'want_response_signed': False,
            },
        },
    }
```
and calling `prepare_for_authenticate` in this way:
```
reqid, info = saml_client.prepare_for_authenticate()
```

I've been digging a bit on it and these are my findings:
* When the `prepare_for_negotiated_authenticate` (`saml/client.py`) is called, there aren't any `kwargs` defined. But in the `try` snippet at line 128 the `sigalg` variable is being initialised always (because when `kwargs["sigalg"]` doesn't exist the except initialises it as `""`). For that reason when the `apply_binding` is called, it will receive a `kwargs={"sigalg": ""}`.
```python
try:
                sigalg = kwargs["sigalg"]
            except KeyError:
                sigalg = ""

            http_info = self.apply_binding(binding, _req_str, destination,
                                           relay_state, sigalg=sigalg)
```
* Then in the `apply_binding`, for the case `BINDING_HTTP_REDIRECT` (which is my case), the `if`statement from below is executed:
```python
if 'sigalg' in kwargs:
                signer = self.sec.sec_backend.get_signer(kwargs['sigalg'])
            else:
                signer = None
```
As the `'sigalg'`will always be present in `kwargs`, the condition is always evaluated as true, but in my case that I'm not using SP signed requests, the `sec_backend` doesn't exists and the error above mentioned is raised.
```
AttributeError: 'NoneType' object has no attribute 'get_signer'
```
I fixed it changing the condition to:
```python
if 'sigalg' in kwargs and kwargs['sigalg'] != '':
                signer = self.sec.sec_backend.get_signer(kwargs['sigalg'])
            else:
                signer = None
```

But as I said it's the first time I'm using `pysaml2`and don't know if I'm doing a bad use of its config. Could you confirm me if I'm doing something wrong or if there's a bug?

Thanks in advance and sorry for the TL;DR

**Comment by julianvilas** [comment]
Fixed in 0e4f5fa48b1965b269f69bd383bbfbde6b41ac63
